---
blank_issues_enabled: false
contact_links:
  - name: LookupIPtoDNSTool Community Support
    url: https://github.com/michaelmsonne/LookupIPtoDNSTool/discussions
    about: Please ask and answer questions here.
